#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    if n % 2 == 1 or n == 1 : 
        print("Weird")
    elif n % 2 == 0 and 5 < n < 22 :
        print("Weird")
    else : 
        print("Not Weird")
